### PR TITLE
Add Polymer2 support, add visual tests

### LINKED ISSUE #27: Polymer 2.0 Support

### LINKED ISSUE #28: Visual Regression Testing

### PR DESCRIPTION
**Pull request by limonte**
Fixes #27 (Polymer2 support)
Fixes #28 (visual tests)

---

**BREAKING CHANGE:** the prefix was changed from `vaadin-icons:` to `vaadin:`

Before:

```html
<iron-icon icon="vaadin-icons:calendar"></iron-icon>
```

After:

```html
<iron-icon icon="vaadin:calendar"></iron-icon>
```

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/29)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[test/visual/default.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfBhRu-89-fUNs5XJDR:-KfBhRu-89-fUNs5XJDS:bnrsu00) ([raw file](https://github.com/vaadin/vaadin-icons/blob/bb3aac328b5e7c6f3d9448b592d204d11c6be4b1/test/visual/default.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

Committed this by accident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by limonte** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/visual/default.html, line 1 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfBhRu-89-fUNs5XJDR:-KfBjZLkC6TRp7cLF8wY:bpw553y) ([raw file](https://github.com/vaadin/vaadin-icons/blob/bb3aac328b5e7c6f3d9448b592d204d11c6be4b1/test/visual/default.html#L1)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Committed this by accident?
</blockquote></details>

oops :) Thanks for catching, removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by manolo** [comment]
Reviewed 6 of 13 files at r1, 3 of 3 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfCVzEvQSq1DtVeb8m3:-KfCVzEvQSq1DtVeb8m4:b-92ny25) ([raw file](https://github.com/vaadin/vaadin-icons/blob/ecbe1c3d65986ff31d041682e94a1586471b46ba/.travis.yml#L12)):*
> ```YAML
> install:
>   - npm install
>   - npm install -g bower
> ```

IMO bower should be a dev dependency in the  package.json so as the first npm run installs it without having to lose time in a second run.
It implies that we take advantage of bower installation being cached.

---

*[package.json, line 28 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfCXlq8HWYJ3psGhv0Z:-KfCXlq8HWYJ3psGhv0_:b-6sw5td) ([raw file](https://github.com/vaadin/vaadin-icons/blob/ecbe1c3d65986ff31d041682e94a1586471b46ba/package.json#L28)):*
> ```JSON
>     "gulp-modify": "latest",
>     "gulp-concat": "latest",
>     "polymer-cli": "0.18.0-pre.13"
> ```

why not use "next" instead as @platosha suggested? so as we check against the latest pre release

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by limonte** [comment]
Review status: 10 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfCVzEvQSq1DtVeb8m3:-KfFrq1pIyjzDzAYByN8:b-a36jdb) ([raw file](https://github.com/vaadin/vaadin-icons/blob/ecbe1c3d65986ff31d041682e94a1586471b46ba/.travis.yml#L12)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

IMO bower should be a dev dependency in the  package.json so as the first npm run installs it without having to lose time in a second run.
It implies that we take advantage of bower installation being cached.

</blockquote></details>

Agree, done.

---

*[package.json, line 28 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfCXlq8HWYJ3psGhv0Z:-KfFrsL5O1dwRW8GX2Fs:b-dtkds3) ([raw file](https://github.com/vaadin/vaadin-icons/blob/ecbe1c3d65986ff31d041682e94a1586471b46ba/package.json#L28)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not use "next" instead as @platosha suggested? so as we check against the latest pre release
</blockquote></details>

Done, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by platosha** [comment]
Reviewed 4 of 13 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[.gitignore, line 3 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGwTUJoCsLpqrs10f0:-KfGwTUJoCsLpqrs10f1:b-e9ee2x) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/.gitignore#L3)):*
> ```
> bower_components*
> node_modules
> bower-*.json
> ```

Probably not needed, since having setup variants in multiple bower-smth.json config files is not the chosen way.

---

*[.travis.yml, line 21 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGvDnyq4iuapaXdxvN:-KfGvDnyq4iuapaXdxvO:b-hg3myz) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/.travis.yml#L21)):*
> ```YAML
>   - rm -rf bower_components
>   - cp bower-polymer2.json bower.json
>   - bower install --quiet --no-color
> ```

`polymer install --variants` should produce two `bower_component-...` directories. We should either swap the directories here, or run `polymer serve` to serve both variants on different ports, and change the port number in gemini `rootUrl` somehow.

Btw, `bower-polymer2.json` missing from this PR now. I guess, now it is actually testing against 1.0 polymer twice.

---

*[vaadin-icons.html, line 7 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGzPK1-KKPybYPEYQ9:-KfGzPK1-KKPybYPEYQA:b-qqo4lx) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/vaadin-icons.html#L7)):*
> ```HTML
>  -->
> 
>  <link rel="import" href="../polymer/polymer.html">
> ```

Polymer is never used in this file. Meaningfully, it is should not be a requirement then.

---

*[vaadin-icons.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyow0f4DLgd1GTwye:-KfGyow0f4DLgd1GTwyf:b-f760w5) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/vaadin-icons.html#L18)):*
> ```HTML
>  use:
>  ```html
>      <link rel="import" href="/bower_components/vaadin-icons/vaadin-icons.html">
> ```

Please use `components`, as required by polymer CLI environment.

---

*[demo/index.html, line 19 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyKuroUpyZdnlcO5m:-KfGyKustodWQtdwiFZF:b-eq8l89) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L19)):*
> ```HTML
>         text-align: center;
>         width: 130px;
>         display: inline-block;
> ```

This was in a flex layout before, why change to inline blocks?

---

*[demo/index.html, line 24 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfH-_VYvL3qlipYO180:-KfH-_VYvL3qlipYO181:b-m2droi) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L24)):*
> ```HTML
>       }
> 
>       .icon-container span {
> ```

Please add some spacing above the icon name. Having zero vertical space between the icon and it’s title looks bad.

The spacing should be small enough, though. `iron-icons` use `.5em`, something like that should be fine.

---

*[demo/index.html, line 39 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfH-84RT_1EtDmSU9aJ:-KfH-84RT_1EtDmSU9aK:b39elag) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L39)):*
> ```HTML
>       .icon-container iron-icon {
>         display: inline-block;
>         width: 48px;
> ```

Too big. Perhaps we should not override default size here. It makes sense that the demo look matches the default `<iron-icon>` look, including its size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by limonte** [comment]
Review status: 5 of 12 files reviewed at latest revision, 10 unresolved discussions.

---

*[.gitignore, line 3 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGwTUJoCsLpqrs10f0:-KfH6-dbCAGoz1XKRtos:b-21tgxx) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/.gitignore#L3)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Probably not needed, since having setup variants in multiple bower-smth.json config files is not the chosen way.
</blockquote></details>

Needed. `polymer install --variants` automatically generates `bower-*.json` files, e.g. `bower-polymer2.json`. Those files should not end up in the repo.

---

*[.travis.yml, line 21 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGvDnyq4iuapaXdxvN:-KfHB_8wL6Wdym1NybnJ:bhexd19) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/.travis.yml#L21)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

`polymer install --variants` should produce two `bower_component-...` directories. We should either swap the directories here, or run `polymer serve` to serve both variants on different ports, and change the port number in gemini `rootUrl` somehow.

Btw, `bower-polymer2.json` missing from this PR now. I guess, now it is actually testing against 1.0 polymer twice.
</blockquote></details>

Done with swapping directories.

---

*[vaadin-icons.html, line 7 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGzPK1-KKPybYPEYQ9:-KfHBcs1ZjeS4kwSqrTO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/vaadin-icons.html#L7)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Polymer is never used in this file. Meaningfully, it is should not be a requirement then.
</blockquote></details>

Done.

---

*[vaadin-icons.html, line 18 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyow0f4DLgd1GTwye:-KfHBdoV7ZY3fIigx484:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/vaadin-icons.html#L18)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Please use `components`, as required by polymer CLI environment.
</blockquote></details>

Done.

---

*[demo/index.html, line 19 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyKuroUpyZdnlcO5m:-KfHClkQiLjd3POxLCje:bjrl77m) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L19)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This was in a flex layout before, why change to inline blocks?
</blockquote></details>

The same result with fewer dependencies and less code.

---

*[demo/index.html, line 24 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfH-_VYvL3qlipYO180:-KfHI1jix8PDN61C3syW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L24)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Please add some spacing above the icon name. Having zero vertical space between the icon and it’s title looks bad.

The spacing should be small enough, though. `iron-icons` use `.5em`, something like that should be fine.
</blockquote></details>

Done.

---

*[demo/index.html, line 39 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfH-84RT_1EtDmSU9aJ:-KfHI2hU5P_tlWyJk3h7:bss4a2b) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L39)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Too big. Perhaps we should not override default size here. It makes sense that the demo look matches the default `<iron-icon>` look, including its size.
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by manolo** [comment]
Fix CI, then :lgtm: 

---

Reviewed 1 of 2 files at r4, 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-:-KfL44RkcbAuEi4zYOQD:b-fpgp51)*

**Comment by platosha** [comment]
Reviewed 8 of 8 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 19 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyKuroUpyZdnlcO5m:-KfL4ZtLZu4Wt3PVBrmO:b8jph65) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L19)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

The same result with fewer dependencies and less code.
</blockquote></details>

It is not required to use `iron-flex-layout` to define a flex layout. The same result with less tricky code, no need of `font-size: 0;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by limonte** [comment]
Review status: 10 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 19 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-KfGyKuroUpyZdnlcO5m:-KfLNmOAyjZ3ktZmQ0uQ:bfzbik4) ([raw file](https://github.com/vaadin/vaadin-icons/blob/320b5ac0eb160ab5772b1768b80ef2fbb83d6f70/demo/index.html#L19)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

It is not required to use `iron-flex-layout` to define a flex layout. The same result with less tricky code, no need of `font-size: 0;`
</blockquote></details>

You're right. Done, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/29#-:-KfM9Lga-OEvbJECJVop:bnfp4nl)*

**Pull request merged**
