### PR TITLE
Add missing dependency. Fixes #52

### LINKED ISSUE #52: v4.1.3 icons demo does not work in CDN

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/58)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[bower.json, line 31 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9sZJMV1ezhxJ91drja:-L9sZJMV1ezhxJ91drjb:b6wx9t8) ([raw file](https://github.com/vaadin/vaadin-icons/blob/33c0d5e792f2c39c874cf5cd725054f61a193703/bower.json#L31)):*
> ```JSON
>     "iron-icon": "^2.0.0",
>     "iron-iconset-svg": "^2.0.0",
>     "vaadin-text-field": "^2.0.0"
> ```

Should be a devDependency

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 31 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9sZJMV1ezhxJ91drja:-L9sZiZ_7gbYmkJBr8d5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/33c0d5e792f2c39c874cf5cd725054f61a193703/bower.json#L31)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should be a devDependency
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by tomivirkki** [comment]
*[.travis.yml, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9s_GXh19uBloDY7dNA:-L9s_GXh19uBloDY7dNB:b8xt949) ([raw file](https://github.com/vaadin/vaadin-icons/blob/8ca4b34fcaf02a47e87aee159b7f8168e7db7850/.travis.yml#L11)):*
> ```YAML
> 
> install:
>   - yarn install
> ```

Why change to yarn?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9s_GXh19uBloDY7dNA:-L9scLpo3jtLpmzZhLIy:btmhl7f) ([raw file](https://github.com/vaadin/vaadin-icons/blob/8ca4b34fcaf02a47e87aee159b7f8168e7db7850/.travis.yml#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why change to yarn?
</blockquote></details>

No idea why `npm i` breaks CI, even after removing travis cache. It works as expected in local. Otherwise i tried yarn and it simply works always. Not sure if we need to spend time investigating or just use yarn.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by web-padawan** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9s_GXh19uBloDY7dNA:-L9sd-330rzEhZjcGIwQ:bmgbffy) ([raw file](https://github.com/vaadin/vaadin-icons/blob/8ca4b34fcaf02a47e87aee159b7f8168e7db7850/.travis.yml#L11)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

No idea why `npm i` breaks CI, even after removing travis cache. It works as expected in local. Otherwise i tried yarn and it simply works always. Not sure if we need to spend time investigating or just use yarn.
</blockquote></details>

pls bump node_js to 8.11 or just `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by tomivirkki** [comment]
*[.travis.yml, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9s_GXh19uBloDY7dNA:-L9sdENd6lSZbx3wS0n8:b-2i08wn) ([raw file](https://github.com/vaadin/vaadin-icons/blob/8ca4b34fcaf02a47e87aee159b7f8168e7db7850/.travis.yml#L11)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

pls bump node_js to 8.11 or just `
</blockquote></details>

8.9 to align with skeleton

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 11 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-L9s_GXh19uBloDY7dNA:-L9sga3p7AJ4nHuvkV44:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-icons/blob/8ca4b34fcaf02a47e87aee159b7f8168e7db7850/.travis.yml#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

8.9 to align with skeleton
</blockquote></details>

Done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-:-L9siouO6k2logUvihYl:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/58#-:-L9skF6630d3yO6Kshui:bnfp4nl)*

**Pull request merged**
