### PR TITLE
Prototype new icons with lit-html literals

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to #81 

WIP, do not merge.

## Description

This is a prototype of possible replacement for `<iron-icon>` in the next Vaadin LTS. It provides the following features:

1. ES module bundle created with Rollup which exports all the icons as `lit-html` tagged literals.
2. Individual files in `icons` folder (not included to Git) which can be imported separately.
3. An entrypoint `vaadin-icons.js` registerering all the icons in the bundle to be used like this:

```html
<vaadin-icon icon="vaadin:user"></vaadin-icon>
````

4. Alternative way of using icons for Fusion and LitElement users with tagged literals:

```js
import { user } from '@vaadin/vaadin-icons/icons/user.js';

html`
  <vaadin-icon .svg="${user}"></vaadin-icon>
`;
```

## Next steps

- [ ] add a new demo and move all the icons there so `index.html` would contain API docs 
- [ ] update visual tests to the new setup with ES modules
- [ ] write unit tests for `vaadin-icon` and `vaadin-iconset`

### CODE REVIEW

**Comment by knoobie** [comment]
Not sure how much you wanna change. Let me just leave a good link about a11y svg here :) https://css-tricks.com/accessible-svgs/#icons

**Comment by web-padawan** [comment]
@knoobie thanks for sharing!

We still need to agree on feature design and definition of done for `vaadin-icons` rewrite but a11y is definitely our priority.

For now I'm going to implement a11y support based on what the [lion-icon](https://github.com/ing-bank/lion/blob/master/packages/icon/src/LionIcon.js) provides:

- `label` property that is used to toggle the `aria-label` attribute
- `role` attribute 
- `aria-hidden` attribute

**Comment by knoobie** [comment]
@web-padawan  Looks promising - the most important part is probably this [method](https://github.com/ing-bank/lion/blob/37f975ea481d2f815d9ddb9e2783cced31291a8c/packages/icon/src/LionIcon.js#L144). Hiding / showing the icon depending on a provided label is a good idea.

**Comment by web-padawan** [comment]
Closing this PR as it was only a prototype. 

I will start working on the actual implementation as part of vaadin/web-components#310

**Pull request closed without merging**
