### PR TITLE
Enable visual tests for Polymer 2

### PR DESCRIPTION
**Pull request by limonte**
:tada:

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/39)

### CODE REVIEW

**Comment by platosha** [comment]
Build error. :smiley: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/39#-:-KmapA0FgH_x_nrLyR6s:b-cldtzm)*

**Comment by limonte** [comment]
It's fine now. Probably that was because both `push` and `pull_request` builds were run at the same time and both builds performing visual tests.

**Comment by limonte** [comment]
> It's fine now. Probably that was because both push and pull_request builds were run at the same time and both builds performing visual tests.

This is fixed now, visual tests will run for `push` and `cron` builds, not for `pull_request`.

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/39#-:-KmfOgTqpZJHsh049rJ5:b-uwkowd)*

**Pull request merged**
