### PR TITLE
Fix icon names to match metadata

### LINKED ISSUE #20: missing icons
vaadin-icons.html

close, close-circle...

thanks

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #20 

Some icons had wrong filenames that did not match the metadata. These were fixed in https://github.com/vaadin/vaadin-icons-files/commit/dc1c218bbd478cf00f3c7cc3581cbd02f28a447b, but looks like the build script of this project was never run after the update. 😞

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/21)

### CODE REVIEW

**Comment by tehapo** [comment]
Updated the original PR with not removing the old icons, but instead keeping them in the end of the file for backwards compatibility.

This will enable releasing 1.0.2 version without breaking any existing apps.

**Comment by tomivirkki** [comment]
Should the new icons be added to the demo also?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/21#-:-KOo9jWVQsqG6a5p3QPH:b-xn4to1)_

**Comment by tomivirkki** [comment]
Oh, sorry, was in the wrong branch

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/21#-:-KOoA9CHaSx4hd4E9xOQ:b5qxxd5)_

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/21#-:-KOoAR7-vv5nylCaQ-1g:bnfp4nl)_

**Pull request merged**
