### PR TITLE
P3 preview

### PR DESCRIPTION
**Pull request by manolo**
Connects to https://github.com/vaadin/components-team-tasks/issues/368

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm: 

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r2, 1 of 4 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-:-LFMoMY-5MY9NJxtZ_bM:bg7igkv)*

**Comment by tomivirkki** [comment]
*[bower.json, line 35 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFMzT8w2Lzwxm-ZgIq1:-LFMzT8x-CqYMWeOqutY:bnh9cga) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/bower.json#L35)):*
> ```JSON
>     "iron-component-page": "^3.0.0",
>     "iron-meta": "^2.0.0",
>     "vaadin-demo-helpers": "vaadin/vaadin-demo-helpers#p3-preview",
> ```

Should not mention p3-preview anymore

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)*

**Comment by tomivirkki** [comment]
*[package.json, line 3 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFNQ5BA4SaPMdDw-D5w:-LFNQ5BA4SaPMdDw-D5x:by9krjg) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/package.json#L3)):*
> ```JSON
> {
>   "name": "@vaadin/vaadin-icons",
>   "version": "4.1.4-pre.2",
> ```

should not be changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @manolo and @tomivirkki)

---

*[bower.json, line 35 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFMzT8w2Lzwxm-ZgIq1:-LFNVKglEcV8bRJ_h-5I:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/bower.json#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should not mention p3-preview anymore
</blockquote></details>

Done.

---

*[package.json, line 3 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFNQ5BA4SaPMdDw-D5w:-LFNVI8o04u4ND2QBeSn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/package.json#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

should not be changed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)*

**Comment by tomivirkki** [comment]
*[bower.json, line 35 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFMzT8w2Lzwxm-ZgIq1:-LFQw5_d1OrK6r29C0NF:b-98mzm8) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/bower.json#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The line below still has it

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)*

**Comment by manolo** [comment]
Review status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @manolo and @tomivirkki)

---

*[bower.json, line 35 at r5](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-LFMzT8w2Lzwxm-ZgIq1:-LFRIrrrCDhY3qEF2-u4:b-sdd7jh) ([raw file](https://github.com/vaadin/vaadin-icons/blob/2fdcb9ea5224b3159f540f121c211113a6b9d386/bower.json#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The line below still has it
</blockquote></details>

Waiting until vaadin-text-field is released 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 6 files at r1, 1 of 2 files at r2, 2 of 4 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/62#-:-LFSOL390fA_jaPKlPxJ:bnfp4nl)*

**Pull request merged**
