### PR TITLE
Depend on Polymer 2 by default

### PR DESCRIPTION
**Pull request by manolo**
Connects to #34

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/35)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower.json, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl7zl249C71dt-dyNz:-Kjl7zl249C71dt-dyO-:b-qal4z) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L27)):*
> ```JSON
>   ],
>   "dependencies": {
>     "polymer": "^2.0.0-rc.2",
> ```

should be `^2.0.0`

---

*[bower.json, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl83Bvu452JOZ7kX00:-Kjl83Bvu452JOZ7kX01:b4seua0) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L35)):*
> ```JSON
>     "iron-meta": "#2.0-preview",
>     "elements-demo-resources": "#2.0-preview",
>     "webcomponentsjs": "#v1"
> ```

remove explicit dependency to `webcomponentsjs`

---

*[bower.json, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl86CN9-pLpz4Ndbhq:-Kjl86CN9-pLpz4Ndbhr:b4seua0) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L43)):*
> ```JSON
>       },
>       "devDependencies": {
>         "webcomponentsjs": "^0.7.24"
> ```

remove explicit dependency to `webcomponentsjs`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[bower.json, line 27 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl7zl249C71dt-dyNz:-KjlLU8beCUN6nizJzYc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L27)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

should be `^2.0.0`
</blockquote></details>

Done.

---

*[bower.json, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl83Bvu452JOZ7kX00:-KjlLUWmneMMxKrqk-Hw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L35)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

remove explicit dependency to `webcomponentsjs`
</blockquote></details>

Done.

---

*[bower.json, line 43 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-Kjl86CN9-pLpz4Ndbhq:-KjlLUz8zzuFOc9xsmOi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/161f4c69b153f1532a0b28612777dc2ee21d8e64/bower.json#L43)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

remove explicit dependency to `webcomponentsjs`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-:-Kjqe4wB4XFTb7ouIaNB:bnfp4nl)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-icons/35#-:-KjrTY1J1y5gJsWujEEo:bnfp4nl)*

**Pull request merged**
