### PR TITLE
Add AsciiDoc documentation

### LINKED ISSUE #7: Add AsciiDoc documentation
Connects to vaadin/components-team-tasks#107

Add AsciiDoc documentation to be included in vaadin.com/docs.

From review meeting notes, this should include:
- Different ways of using in different frameworks
- List of included icons (including picture, core, svg file name, ligature)

### PR DESCRIPTION
**Pull request by tehapo**
Fixes #7

Connects to vaadin/components-team-tasks#107

Separated the change into two commits.
1. Commit https://github.com/vaadin/vaadin-icons/pull/8/commits/f7fe0841f66e3a3439580eb6f4c5acf880256bb3 contains only added PNG files (no need for a review).
2. Commit https://github.com/vaadin/vaadin-icons/pull/8/commits/6b4232f9255356c3651ffd27067e8023bf940d39 contains changes to gulpfile.js and the added documentation (review this one).

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/8)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm: 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-:-KD3X037vJP6rdR4_o_V:980077423)_

**Comment by manolo** [comment]
Review status: 0 of 532 files reviewed at latest revision, 1 unresolved discussion.

---

_[docs/vaadin-icons-overview.adoc, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7Zj_3Z6-RlcCcaf8C:-KD7Zj_3Z6-RlcCcaf8D:-1618050643) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L10)):_
IIRC  saxon genitive should not be used when people are not involved in the sentence. I would rather 'with  the Polymer iron-icon element', but @magi42 could have a better opinion  about saxon usage

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8)_

**Comment by manolo** [comment]
Review status: 0 of 532 files reviewed at latest revision, 4 unresolved discussions.

---

_[docs/vaadin-icons-overview.adoc, line 11 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7_rpzICrCBS_pR24q:-KD7_rpzICrCBS_pR24r:700863875) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L11)):_
'icon' word appears too many times in this phrase.

---

_[docs/vaadin-icons-overview.adoc, line 22 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7a9e-Bx6vxWbukJoe:-KD7a9e-Bx6vxWbukJof:-465804168) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L22)):_
'as a font icon' -> as a font.
I guess comma before or

---

_[docs/vaadin-icons-overview.adoc, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7aWW-gz-fdra2h1--:-KD7aWW-gz-fdra2h1-0:-1958284253) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L28)):_
The following ..

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8)_

**Comment by manolo** [comment]
I feel like a page with 500 images would take a long to load, specially in slow devices. Have you tested performance load ?

---

Review status: 0 of 532 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-:-KD7axb7uzBjJ9VaQAmC:-195754146)_

**Comment by tehapo** [comment]
Review status: 0 of 532 files reviewed at latest revision, 4 unresolved discussions.

---

_[docs/vaadin-icons-overview.adoc, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7Zj_3Z6-RlcCcaf8C:-KDIFXscyMhILEa90hCs:1882448717) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L10)):_
Done. Rephrased the sentence a bit.

---

_[docs/vaadin-icons-overview.adoc, line 11 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7_rpzICrCBS_pR24q:-KDIFgK9PG7SYfAo3tv9:1882448717) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L11)):_
Done. Rephrased the sentence a bit.

---

_[docs/vaadin-icons-overview.adoc, line 22 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7a9e-Bx6vxWbukJoe:-KDIFi6FPetfd7NUiTJB:1038517228) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L22)):_
Changed the "font icon" to "font file" to be more clear.

---

_[docs/vaadin-icons-overview.adoc, line 28 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD7aWW-gz-fdra2h1--:-KDIFstpx9flncjgwxsg:-499146009) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L28)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8)_

**Comment by tehapo** [comment]
The performance is a good question. I did not test the performance yet. A more lightweight option would be to have the font file included in the page and have the icons displayed from the font.

---

Review status: 0 of 532 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-:-KDIG0DifzXFpX0l5W5r:-1212271824)_

**Comment by tehapo** [comment]
@magi42 – could you also take a look at this PR?

**Comment by tehapo** [comment]
Tested an HTML rendering of the page on my Nexus 5 phone and the page rendering performance was fine even while the page has 500+ PNG images.

**Comment by manolo** [comment]
:lgtm:

---

Review status: 0 of 532 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-:-KDOZjUiRnQ7lF5Zbqkx:1417088721)_

**Comment by manolo** [comment]
Reviewed 531 of 532 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8)_

**Comment by magi42** [comment]
Reviewed 531 of 532 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

_[docs/vaadin-icons-overview.adoc, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD3X5yrHvrJZfq640Mi:-KD3X5yrHvrJZfq640Mj:-666520008) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L10)):_
- `<vaadin-icons>` is a name, so it can't have article as such. Maybe rather: "The [vaadinelement]#vaadin-icons# collection is..." (although repeating collection and set is a bit odd.)

---

_[docs/vaadin-icons-overview.adoc, line 11 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD3XdUFX7tjCmBMOB12:-KD3XdUG54qAPw3SlQ9S:-1700131721) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L11)):_
- You're not using just one icon, so rather "the icon" -> "_an icon_"

---

_[docs/vaadin-icons-overview.adoc, line 12 [r1]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KD3XpUPaK1MXz9FN-tv:-KD3XpUPaK1MXz9FN-tw:1897327310) ([raw file](https://github.com/vaadin/vaadin-icons/blob/6b4232f9255356c3651ffd27067e8023bf940d39/docs/vaadin-icons-overview.adoc#L12)):_
- Maybe rather "_elements that support icons_"
- The word "like" is used for comparison, not examples, and in that use it would mean same as "for example". Hence rather: "icons, for example, [elementname]#paper-fab#." (Note the comma after "for example")

---

_[docs/vaadin-icons-overview.adoc, line 29 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8#-KDTWdMvXfAfHFQKvq8E:-KDTWdMvXfAfHFQKvq8F:629627160) ([raw file](https://github.com/vaadin/vaadin-icons/blob/aaed6f4ef28eed33fb77bde7b0f5e1551523c5e1/docs/vaadin-icons-overview.adoc#L29)):_
The table doesn't include anything else but the icons, so it doesn't just include a list of the icons, it rather lists them. So: "The following table lists the icons currently available"

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/8)_

**Pull request merged**
