### PR TITLE
Feature/readme

### LINKED ISSUE #2: Rewrite readme and demo/documentation
Readme:
- Short description
- Link to vaadin.com/elements (to the icons section)
- Link to vaadin.com/icons, if someone wants to use the icons in some other format
- Screenshot
- How to use / getting started
- License

Demo/documentation:
- Can follow the same outline as the readme
- Link to sources in GitHub

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #2

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/4)

### CODE REVIEW

**Comment by tehapo** [comment]
The README file does not have a link to the marketing page as was instructed in the ticket.
https://vaadin.com/elements/-/element/vaadin-icons

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 9 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8c4_JftSSgAAYfUcq9:-K8c4_JftSSgAAYfUcqA:-2123210921) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L9)):_
I would prefer to see a screenshot taken with a retina screen and then forced to half-size with the `width` attribute. Current one looks blurry on a retina screen.

---

_[vaadin-icons.html, line 11 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8c60JM1EArb9FSk7Rn:-K8c60JM1EArb9FSk7Ro:-1459116517) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/vaadin-icons.html#L11)):_
Maybe the `iron-icon` could be a link to https://elements.polymer-project.org/elements/iron-icon

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-:-K8c5HY0Z01xoBCJckrF:-1509523293)_

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 14 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cCM-pOeHw3NmV2_h6:-K8cCM-qCBp3Lh7U9XuJ:-1049826419) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L14)):_
I would say something about that it is compatible with any component using iron-icon and exposing the `icon` attribute (i.e. paper-fab)

---

_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8cDIOb660_EnNqhgFm:1712907140) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
I would explain this,  for new people coming to this page could be confusing what this means. 
Something like `vaadin-icons` is based on vaadin icons collection, there is a process to download all the icons and bundle them as this web component.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by Saulis** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 9 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8c4_JftSSgAAYfUcq9:-K8cDaYnwYHRIFM0jakf:-499146009) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L9)):_
Done.

---

_[README.md, line 14 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cCM-pOeHw3NmV2_h6:-K8cGvqw1pw1Bja3EPyv:-499146009) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L14)):_
Done.

---

_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8cH9DT0LuZAdFhEFZ3:1280173727) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
Yeah.. I was thinking if we should actually remove this section? Is this something we expect external developers to do? @tehapo @jounik ?

---

_[vaadin-icons.html, line 11 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8c60JM1EArb9FSk7Rn:-K8cIW1DQw8EqeN57GzD:-499146009) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/vaadin-icons.html#L11)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by jouni** [comment]
_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8cMahry5UjDmUvsW62:-48298285) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
I would remove it at least for now.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by manolo** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8cKuip6YmwBnOTmEFK:382823007) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
+1 for removing that. We could leave a comment in the gulpfile just for the components developers.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8c_YQ5bbdt__jC-16w:-1011065476) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
Sure, I'm also ok with removing this section.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by Saulis** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 39 [r2]](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-K8cDIOb660_EnNqhgFl:-K8cwFPOhN7GxYfx0Qrd:-499146009) ([raw file](https://github.com/vaadin/vaadin-icons/blob/1d7f19f7bd473082a6cc35128e3570a751c6ed9c/README.md#L39)):_
Done.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Comment by tehapo** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4#-:-K8d4_KO2_PAPqCo9f3K:980077423)_

**Comment by tehapo** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-icons/4)_

**Pull request merged**
