### PR TITLE
P3 preview dev

### LINKED ISSUE #54: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by yuriy-fix**
Fixes #54

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-icons/56)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 7 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[.travis.yml, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-L9L2uWw0uE-xGKWUgfe:-L9L2uWw0uE-xGKWUgff:b-1idc7c) ([raw file](https://github.com/vaadin/vaadin-icons/blob/704c9b30975c448516c29a1d8585cf5456d142ce/.travis.yml#L4)):*
> ```YAML
> dist: trusty
> language: node_js
> node_js: 8.0
> ```

Too old for `magi-cli`, errors in Travis. Please bump this number.

---

*[.travis.yml, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-L9L3AlB5MlDXdZjG0WL:-L9L3AlB5MlDXdZjG0WM:bafdn7n) ([raw file](https://github.com/vaadin/vaadin-icons/blob/704c9b30975c448516c29a1d8585cf5456d142ce/.travis.yml#L22)):*
> ```YAML
>       npm install -g polymer-cli &&
>       npm install &&
>       gulp lint version:check &&
> ```

Apparently there are no tasks for `lint` and `version check` in the `gulpfile.js`, but it errors in Travis. No need for this line.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56)*

**Comment by yuriy-fix** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 4 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-L9L2uWw0uE-xGKWUgfe:-L9Oy99l6vDnmwAIfDTi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/704c9b30975c448516c29a1d8585cf5456d142ce/.travis.yml#L4)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Too old for `magi-cli`, errors in Travis. Please bump this number.
</blockquote></details>

Done.

---

*[.travis.yml, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-L9L3AlB5MlDXdZjG0WL:-L9Oy9VR956a1f1j7asx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-icons/blob/704c9b30975c448516c29a1d8585cf5456d142ce/.travis.yml#L22)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Apparently there are no tasks for `lint` and `version check` in the `gulpfile.js`, but it errors in Travis. No need for this line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-:-L9PH7AI9r8AGDPQ8mtb:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-icons/56#-:-L9eWLmu4EATgfqwUf8G:bnfp4nl)*

**Pull request merged**
